items:
  - "STONE"
  - "COBBLESTONE"
  - "DIRT"
  - "IRON_INGOT"
  - "GOLD_INGOT"
  - "DIAMOND"
  - "EMERALD"
  - "IRON_SWORD"
  - "DIAMOND_SWORD"
  - "WOODEN_PICKAXE"
  - "STONE_PICKAXE"
  - "IRON_PICKAXE"
  - "DIAMOND_PICKAXE"
  - "GOLDEN_APPLE"
  - "ENCHANTED_GOLDEN_APPLE"
  - "BOW"
  - "ARROW"
  - "SHIELD"
  - "IRON_HELMET"
  - "IRON_CHESTPLATE"
  - "IRON_LEGGINGS"
  - "IRON_BOOTS"
  - "DIAMOND_HELMET"
  - "DIAMOND_CHESTPLATE"
  - "DIAMOND_LEGGINGS"
  - "DIAMOND_BOOTS"
  - "GOLDEN_HELMET"
  - "GOLDEN_CHESTPLATE"
  - "GOLDEN_LEGGINGS"
  - "GOLDEN_BOOTS"
  - "LEATHER_HELMET"
  - "LEATHER_CHESTPLATE"
  - "LEATHER_LEGGINGS"
  - "LEATHER_BOOTS"
  - "CHAINMAIL_HELMET"
  - "CHAINMAIL_CHESTPLATE"
  - "CHAINMAIL_LEGGINGS"
  - "CHAINMAIL_BOOTS"
  - "OBSIDIAN"
  - "BOOK"
  - "ENCHANTED_BOOK"
  - "EXPERIENCE_BOTTLE"
  - "ENDER_PEARL"
  - "BLAZE_ROD"
  - "NETHER_WART"
  - "POTION"
  - "ENDER_EYE"
  - "SADDLE"
  - "HORSE_ARMOR"
  - "TNT"
  - "FLINT_AND_STEEL"
  - "WATER_BUCKET"
  - "LAVA_BUCKET"
  - "MILK_BUCKET"
  - "BREAD"
  - "STEAK"
  - "COOKED_CHICKEN"
  - "COOKED_PORKCHOP"
  - "CARROT"
  - "POTATO"
  - "GOLDEN_CARROT"
  - "APPLE"
  - "COAL"
  - "CHARCOAL"
  - "TORCH"
  - "LADDER"
  - "FISHING_ROD"
  - "STRING"
  - "FEATHER"
  - "FLINT"
  - "STICK"
  - "CRAFTING_TABLE"
  - "FURNACE"
  - "ANVIL"
  - "BED"
  - "CHEST"
  - "TRAPPED_CHEST"
  - "ENDER_CHEST"
  - "SHULKER_BOX"
  - "PAPER"
  - "COMPASS"
  - "CLOCK"
  - "MAP"
  - "LEAD"
  - "NAME_TAG"
  - "SUGAR"
  - "SUGAR_CANE"
  - "BONE"
  - "GUNPOWDER"
  - "REDSTONE"
  - "LAPIS_LAZULI"
  - "QUARTZ"
  - "CLAY_BALL"
  - "BRICK"
  - "NETHER_BRICK"
  - "GLOWSTONE_DUST"
  - "MAGMA_CREAM"
  - "SLIME_BALL"
  - "GHAST_TEAR"
  - "SPIDER_EYE"
  - "FERMENTED_SPIDER_EYE"
  - "ROTTEN_FLESH"
  - "PRISMARINE_SHARD"
  - "PRISMARINE_CRYSTALS"
  - "BEACON"
  - "SEA_LANTERN"
  - "HEART_OF_THE_SEA"
  - "TURTLE_HELMET"
  - "SCUTE"
  - "NAUTILUS_SHELL"
  - "TOTEM_OF_UNDYING"
  - "MUSIC_DISC"
  - "BOOKSHELF"
  - "PISTON"
  - "STICKY_PISTON"
  - "OBSERVER"
  - "HOPPER"
  - "DROPPER"
  - "DISPENSER"
  - "NOTE_BLOCK"
  - "JUKEBOX"
  - "REDSTONE_TORCH"
  - "LEVER"
  - "REPEATER"
  - "COMPARATOR"
  - "REDSTONE_LAMP"
  - "TRIPWIRE_HOOK"
  - "DAYLIGHT_DETECTOR"
  - "RAIL"
  - "POWERED_RAIL"
  - "DETECTOR_RAIL"
  - "ACTIVATOR_RAIL"
  - "MINECART"
  - "CHEST_MINECART"
  - "HOPPER_MINECART"
  - "FURNACE_MINECART"
  - "TNT_MINECART"
  - "COMMAND_BLOCK_MINECART"
